### ISSUE TITLE
css composement tools 

### ISSUE THREAD

**Issue by Macroldj** [Macroldj/MacroScrapy#1]
1.  xpath 
2. css

**Comment by macroldj** [comment]
1. 使用xpath

**Comment by macroldj** [comment]
[css 方法](https://www.w3school.com.cn/css/css_selector_id.asp)  就是相关css设置的反向操作

**Comment by macroldj** [comment]
最佳实践， 在网页上的一段文字，或者一个页面在进行构建的时候是可以进多种多样的使用方法。反之在进行相关的网页解析的时候也是可以进行多种方法实现解析，在进行定位的时候怎样处理才能更加的稳定，不会随着网页的变化而变化，这就是要在相关的实践中注意的事情。
