### ISSUE TITLE
Proejct about scripy

### ISSUE THREAD

**Issue by Macroldj** [Macroldj/MacroScrapy#5]
1.  友好的开发环境一键部署化境(docker-compose)
2. 容易扩展，通用，以继进行中间件集成
3. 更好的数据库操作。

**Comment by macroldj** [comment]
目录结构 
- domeProjeect 
   - webA 
      - spides 
      - items
      - middlewares
      - piplines 
      - settings
   - main.py (自己定义的debug 文件)
   - requriements.txt

**Comment by macroldj** [comment]
main.py debug 进行degub 调试程序。
